### ISSUE TITLE
How to call C sharp functions from javascript in CefNet.Avalonia?

### ISSUE THREAD

**Issue by strongelf** [Haltroy/CefNet.Avalonia.Examples#2]
How to call C sharp functions from javascript in CefNet.Avalonia?

**Comment by Haltroy** [comment]
Look up [CefAppImpl.cs](https://github.com/Haltroy/CefNet.Avalonia.Examples/blob/main/CefNet.Avalonia.Example/CefAppImpl.cs).
You have to create a new class inheriting `CefV8Handler` class and register it [like in here](https://github.com/Haltroy/CefNet.Avalonia.Examples/blob/main/CefNet.Avalonia.Example/CefAppImpl.cs#L45). (I accdientally left my super old code there for notifications)

Also, the original CefNet project is dead and I strongly recommend using something else (like CefGlue). I don't maintain CefNet.
